[package]
name = "merge_derive"
version = "0.159.4"
authors = ["Jay Anslow <jay@anslow.me.uk>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "0.15"
quote = "0.6"
proc-macro2 = "0.4.20"
